import MobileBottomNav from '@/components/common/navigation/mobile-navigation'
import Footer from '@/components/footer'
import AppProviders from '@/providers/AppProviders'
// import '@/styles/globals.css';
import '@/styles/styles.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'Propublic',
    template: '%s - Propublic',
  },
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.ico', sizes: 'any' }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative max-h-screen h-screen`}
      >
        <AppProviders>
          {/* Header */}
          {/* Cotnent */}
          {children}
          {/* Footer */}
          <Footer />
          {/* Bottom Navbar */}
          <MobileBottomNav />
        </AppProviders>
      </body>
    </html>
  )
}
