import MobileBottomNav from '@shared/components/layout/navigation/mobile-navigation'
import AppProviders from '@/providers/AppProviders'
// import '@/styles/globals.css';
// import '@/styles/styles.css'
import '@/styles/styles.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'Propublic',
    template: '%s - Propublic',
  },
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.ico', sizes: 'any' }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={` ${interSans.variable}} bg-dark-primary text-cream font-display antialiased`}
      >
        <AppProviders>
          {/* Header */}
          {/* Content */}
          {children}
          {/* Footer */}

          {/* Bottom Navbar */}
          <MobileBottomNav />
        </AppProviders>
      </body>
    </html>
  )
}
