import type {
  CarouselGameItem,
  ICourseItem,
  TypeCommunityItem,
} from '@/types/home.types'

export const GAMELIST: CarouselGameItem[] = [
  {
    id: 1,
    name: 'Valorant',
    slug: 'valorant',
    path: '/games/valorant',
    imageSrc: '/images/game-covers/valorant.jpg',
  },
  {
    id: 2,
    name: 'Apex Legends',
    slug: 'apex-legends',
    path: '/games/apex-legends',
    imageSrc: '/images/game-covers/apex-legends.jpg',
  },
  {
    id: 3,
    name: 'Mobile Legends',
    slug: 'mobile-legends',
    path: '/games/mobile-legends',
    imageSrc: '/images/game-covers/mobile-legends.jpg',
  },
  {
    id: 4,
    name: 'Dota 2',
    slug: 'dota-2',
    path: '/games/dota-2',
    imageSrc: '/images/game-covers/dota-2.jpg',
  },
  {
    id: 5,
    name: 'EA FC',
    slug: 'eafc',
    path: '/games/eafc',
    imageSrc: '/images/game-covers/eafc.jpg',
  },
  {
    id: 6,
    name: 'League of Legends',
    slug: 'league-of-legends',
    path: '/games/league-of-legends',
    imageSrc: '/images/game-covers/league-of-legends.jpg',
  },
  {
    id: 7,
    name: 'Fortnite',
    slug: 'fortnite',
    path: '/games/fortnite',
    imageSrc: '/images/game-covers/fortnite.jpg',
  },
  {
    id: 8,
    name: 'Tekken 8',
    slug: 'tekken-8',
    path: '/games/tekken-8',
    imageSrc: '/images/game-covers/tekken-8.jpg',
  },
] as const

export const COURSES: ICourseItem[] = [
  {
    course_id: 4,
    course_title: ' path to pro, jakarta - offline',
    course_slug: 'path-to-pro-jakarta-offline',
    course_description:
      '<p>Level up your esports career in just 4 intensive lessons (6 hours each)—just like how the pros do it. Train with access to pro scrims, deep match analysis, monthly performance reviews, career coaching, and real tryout opportunities with MPL/MDL teams.</p><p><br></p><h3><strong>Disclaimer</strong></h3><ol><li>Minimum Quota Requirement: A minimum of 10 students is required for the class to commence. If the quota is not met, the class may be rescheduled or canceled.</li><li>Refund or Credit Clause: In the event of cancellation due to low enrollment, participants will receive a full refund or credit towards a future class of equal value.</li><li>Tentative Schedule: Class schedule and session dates are tentative and subject to change based on participant count and coach availability.</li><li>Notification Clause: Participants will be notified at least 5 days in advance if the class will not proceed due to unmet minimum requirements.</li></ol>',
    course_image_url:
      'https://propublic-academy.s3.amazonaws.com/course/1747323402_Scarletto.png',
    course_price: '4000000.00',
    order_count: '3',
    course_rating: '0.0000',
  },
  {
    course_id: 1,
    course_title: '1:1 vip coaching - head instuctor: zeys ',
    course_slug: '1:1-vip-coaching-head-instuctor:-zeys',
    course_description:
      '<p>Train with a world-class coach, world champion, and former national team head coach. Get personalized insights, pro-level gameplay analysis, and tailored strategies to reach your goals. Perfect for players serious about leveling up.</p>',
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1747323432_Scarletto.png',
    course_price: '500000.00',
    order_count: '1',
    course_rating: '0.0000',
  },
  {
    course_id: 6,
    course_title: 'test',
    course_slug: 'test',
    course_description: null,
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1750096142_propublic.jpg',
    course_price: '16283000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
  {
    course_id: 5,
    course_title: 'test',
    course_slug: 'test',
    course_description: null,
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1747409832_Scarletto.png',
    course_price: '16493000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
  {
    course_id: 3,
    course_title: 'rank up - online',
    course_slug: 'rank-up-online',
    course_description:
      "<p>Become a rank god and break past the Mythical wall with 4 high-impact online sessions (3 hours each). Whether you're aiming to go semi-pro in community tournaments or just want to carry your friends and dominate ranked, you'll train like the best—exclusive pro scrims, advanced mechanics, and winning strategies included.</p>",
    course_image_url:
      'https://propublic-academy.s3.amazonaws.com/course/1747323413_Scarletto.png',
    course_price: '490000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
] as const

export const COMMUNITIES: TypeCommunityItem[] = [
  {
    id: 1,
    name: 'Elite Gaming Masters',
    description: 'Mastering the art of competitive gaming',
    author: 'elon',
    members: 1247,
    posts: 89,
    sessions: 12,
    guides: 5,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    isFeatured: true,
    color: 'from-red-600 to-red-700',
    headerImage:
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=200&fit=crop',
  },
  {
    id: 2,
    name: 'Pixel Pioneers',
    description: 'Exploring indie games and hidden gems',
    author: 'gamedev_guru',
    members: 589,
    posts: 42,
    sessions: 8,
    guides: 3,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: false,
    color: 'from-blue-500 to-blue-600',
    headerImage:
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=200&fit=crop',
  },
  {
    id: 3,
    name: 'Strategy Nexus',
    description: 'Deep dives into real-time strategy and turn-based tactics',
    author: 'tactician_x',
    members: 912,
    posts: 67,
    sessions: 10,
    guides: 7,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-green-600 to-green-700',
    headerImage:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop',
  },
  {
    id: 4,
    name: 'Esports Fanatics',
    description: 'Following the latest in professional gaming tournaments',
    author: 'esports_insider',
    members: 2300,
    posts: 150,
    sessions: 20,
    guides: 10,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-purple-600 to-purple-700',
    headerImage:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=200&fit=crop',
  },
  {
    id: 5,
    name: 'Retro Game Revival',
    description: 'Celebrating classic games from the 80s and 90s',
    author: 'vintage_gamer',
    members: 765,
    posts: 55,
    sessions: 6,
    guides: 2,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: false,
    color: 'from-yellow-500 to-yellow-600',
    headerImage:
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=200&fit=crop',
  },
  {
    id: 6,
    name: 'RPG Storytellers',
    description: 'Crafting epic tales in role-playing games',
    author: 'lore_master',
    members: 1050,
    posts: 78,
    sessions: 15,
    guides: 8,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-indigo-600 to-indigo-700',
    headerImage:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=200&fit=crop',
  },
]
