import type {
  Brand,
  CarouselGameItem,
  ICourseItem,
  TypeCommunityItem,
} from '@/types/home.types'

export const GAMELIST: CarouselGameItem[] = [
  {
    id: 1,
    name: 'Valorant',
    slug: 'valorant',
    path: '/game/valorant',
    imageSrc: '/images/game-covers/valorant.jpg',
  },
  {
    id: 2,
    name: 'Apex Legends',
    slug: 'apex-legends',
    path: '/game/apex-legends',
    imageSrc: '/images/game-covers/apex-legends.jpg',
  },
  {
    id: 3,
    name: 'Mobile Legends',
    slug: 'mobile-legends',
    path: '/game/mobile-legends',
    imageSrc: '/images/game-covers/mobile-legends.jpg',
  },
  {
    id: 4,
    name: 'Dota 2',
    slug: 'dota-2',
    path: '/game/dota-2',
    imageSrc: '/images/game-covers/dota-2.jpg',
  },
  {
    id: 5,
    name: 'EA FC',
    slug: 'eafc',
    path: '/game/eafc',
    imageSrc: '/images/game-covers/eafc.jpg',
  },
  {
    id: 6,
    name: 'League of Legends',
    slug: 'league-of-legends',
    path: '/game/league-of-legends',
    imageSrc: '/images/game-covers/league-of-legends.jpg',
  },
  {
    id: 7,
    name: 'Fortnite',
    slug: 'fortnite',
    path: '/game/fortnite',
    imageSrc: '/images/game-covers/fortnite.jpg',
  },
  {
    id: 8,
    name: 'Tekken 8',
    slug: 'tekken-8',
    path: '/game/tekken-8',
    imageSrc: '/images/game-covers/tekken-8.jpg',
  },
  {
    id: 9,
    name: 'Overwatch 2',
    slug: 'overwatch-2',
    path: '/game/overwatch-2',
    imageSrc: '/images/game-covers/overwatch-2.jpg',
  },
  {
    id: 10,
    name: 'Call of Duty: Warzone',
    slug: 'call-of-duty-warzone',
    path: '/game/call-of-duty-warzone',
    imageSrc: '/images/game-covers/call-of-duty-warzone.jpg',
  },
  {
    id: 11,
    name: 'Genshin Impact',
    slug: 'genshin-impact',
    path: '/game/genshin-impact',
    imageSrc: '/images/game-covers/genshin-impact.jpg',
  },
  {
    id: 12,
    name: 'Minecraft',
    slug: 'minecraft',
    path: '/game/minecraft',
    imageSrc: '/images/game-covers/minecraft.jpg',
  },
  {
    id: 13,
    name: 'Rocket League',
    slug: 'rocket-league',
    path: '/game/rocket-league',
    imageSrc: '/images/game-covers/rocket-league.jpg',
  },
  {
    id: 14,
    name: 'Grand Theft Auto V',
    slug: 'grand-theft-auto-v',
    path: '/game/grand-theft-auto-v',
    imageSrc: '/images/game-covers/grand-theft-auto-v.jpg',
  },
  {
    id: 15,
    name: 'Cyberpunk 2077',
    slug: 'cyberpunk-2077',
    path: '/game/cyberpunk-2077',
    imageSrc: '/images/game-covers/cyberpunk-2077.jpg',
  },
  {
    id: 16,
    name: 'The Witcher 3: Wild Hunt',
    slug: 'the-witcher-3-wild-hunt',
    path: '/game/the-witcher-3-wild-hunt',
    imageSrc: '/images/game-covers/the-witcher-3-wild-hunt.jpg',
  },
  {
    id: 17,
    name: 'Red Dead Redemption 2',
    slug: 'red-dead-redemption-2',
    path: '/game/red-dead-redemption-2',
    imageSrc: '/images/game-covers/red-dead-redemption-2.jpg',
  },
  {
    id: 18,
    name: 'Elden Ring',
    slug: 'elden-ring',
    path: '/game/elden-ring',
    imageSrc: '/images/game-covers/elden-ring.jpg',
  },
  {
    id: 19,
    name: 'God of War Ragnarök',
    slug: 'god-of-war-ragnarok',
    path: '/game/god-of-war-ragnarok',
    imageSrc: '/images/game-covers/god-of-war-ragnarok.jpg',
  },
  {
    id: 20,
    name: 'Starfield',
    slug: 'starfield',
    path: '/game/starfield',
    imageSrc: '/images/game-covers/starfield.jpg',
  },
  {
    id: 21,
    name: 'Diablo IV',
    slug: 'diablo-iv',
    path: '/game/diablo-iv',
    imageSrc: '/images/game-covers/diablo-iv.jpg',
  },
  {
    id: 22,
    name: 'Hogwarts Legacy',
    slug: 'hogwarts-legacy',
    path: '/game/hogwarts-legacy',
    imageSrc: '/images/game-covers/hogwarts-legacy.jpg',
  },
  {
    id: 23,
    name: 'Final Fantasy VII Rebirth',
    slug: 'final-fantasy-vii-rebirth',
    path: '/game/final-fantasy-vii-rebirth',
    imageSrc: '/images/game-covers/final-fantasy-vii-rebirth.jpg',
  },
  {
    id: 24,
    name: "Baldur's Gate 3",
    slug: 'baldurs-gate-3',
    path: '/game/baldurs-gate-3',
    imageSrc: '/images/game-covers/baldurs-gate-3.jpg',
  },
  {
    id: 25,
    name: 'Spiderman 2',
    slug: 'spiderman-2',
    path: '/game/spiderman-2',
    imageSrc: '/images/game-covers/spiderman-2.jpg',
  },
  {
    id: 26,
    name: 'The Legend of Zelda: Tears of the Kingdom',
    slug: 'the-legend-of-zelda-tears-of-the-kingdom',
    path: '/game/the-legend-of-zelda-tears-of-the-kingdom',
    imageSrc:
      '/images/game-covers/the-legend-of-zelda-tears-of-the-kingdom.jpg',
  },
  {
    id: 27,
    name: 'Resident Evil 4 Remake',
    slug: 'resident-evil-4-remake',
    path: '/game/resident-evil-4-remake',
    imageSrc: '/images/game-covers/resident-evil-4-remake.jpg',
  },
  {
    id: 28,
    name: 'Street Fighter 6',
    slug: 'street-fighter-6',
    path: '/game/street-fighter-6',
    imageSrc: '/images/game-covers/street-fighter-6.jpg',
  },
  {
    id: 29,
    name: 'Alan Wake 2',
    slug: 'alan-wake-2',
    path: '/game/alan-wake-2',
    imageSrc: '/images/game-covers/alan-wake-2.jpg',
  },
  {
    id: 30,
    name: 'Doom Eternal',
    slug: 'doom-eternal',
    path: '/game/doom-eternal',
    imageSrc: '/images/game-covers/doom-eternal.jpg',
  },
  {
    id: 31,
    name: 'Horizon Forbidden West',
    slug: 'horizon-forbidden-west',
    path: '/game/horizon-forbidden-west',
    imageSrc: '/images/game-covers/horizon-forbidden-west.jpg',
  },
  {
    id: 32,
    name: 'Fall Guys',
    slug: 'fall-guys',
    path: '/game/fall-guys',
    imageSrc: '/images/game-covers/fall-guys.jpg',
  },
  {
    id: 33,
    name: 'Among Us',
    slug: 'among-us',
    path: '/game/among-us',
    imageSrc: '/images/game-covers/among-us.jpg',
  },
  {
    id: 34,
    name: 'Stardew Valley',
    slug: 'stardew-valley',
    path: '/game/stardew-valley',
    imageSrc: '/images/game-covers/stardew-valley.jpg',
  },
  {
    id: 35,
    name: 'Terraria',
    slug: 'terraria',
    path: '/game/terraria',
    imageSrc: '/images/game-covers/terraria.jpg',
  },
  {
    id: 36,
    name: 'Rainbow Six Siege',
    slug: 'rainbow-six-siege',
    path: '/game/rainbow-six-siege',
    imageSrc: '/images/game-covers/rainbow-six-siege.jpg',
  },
  {
    id: 37,
    name: 'CS2 (Counter-Strike 2)',
    slug: 'cs2',
    path: '/game/cs2',
    imageSrc: '/images/game-covers/cs2.jpg',
  },
  {
    id: 38,
    name: 'Dead by Daylight',
    slug: 'dead-by-daylight',
    path: '/game/dead-by-daylight',
    imageSrc: '/images/game-covers/dead-by-daylight.jpg',
  },
  {
    id: 39,
    name: 'Teamfight Tactics',
    slug: 'teamfight-tactics',
    path: '/game/teamfight-tactics',
    imageSrc: '/images/game-covers/teamfight-tactics.jpg',
  },
  {
    id: 40,
    name: 'PUBG: Battlegrounds',
    slug: 'pubg-battlegrounds',
    path: '/game/pubg-battlegrounds',
    imageSrc: '/images/game-covers/pubg-battlegrounds.jpg',
  },
  {
    id: 41,
    name: 'Palworld',
    slug: 'palworld',
    path: '/game/palworld',
    imageSrc: '/images/game-covers/palworld.jpg',
  },
  {
    id: 42,
    name: 'Helldivers 2',
    slug: 'helldivers-2',
    path: '/game/helldivers-2',
    imageSrc: '/images/game-covers/helldivers-2.jpg',
  },
  {
    id: 43,
    name: "Dragon's Dogma 2",
    slug: 'dragons-dogma-2',
    path: '/game/dragons-dogma-2',
    imageSrc: '/images/game-covers/dragons-dogma-2.jpg',
  },
  {
    id: 44,
    name: 'Persona 3 Reload',
    slug: 'persona-3-reload',
    path: '/game/persona-3-reload',
    imageSrc: '/images/game-covers/persona-3-reload.jpg',
  },
  {
    id: 45,
    name: 'Prince of Persia: The Lost Crown',
    slug: 'prince-of-persia-the-lost-crown',
    path: '/game/prince-of-persia-the-lost-crown',
    imageSrc: '/images/game-covers/prince-of-persia-the-lost-crown.jpg',
  },
  {
    id: 46,
    name: 'Enshrouded',
    slug: 'enshrouded',
    path: '/game/enshrouded',
    imageSrc: '/images/game-covers/enshrouded.jpg',
  },
  {
    id: 47,
    name: 'Final Fantasy XIV',
    slug: 'final-fantasy-xiv',
    path: '/game/final-fantasy-xiv',
    imageSrc: '/images/game-covers/final-fantasy-xiv.jpg',
  },
  {
    id: 48,
    name: 'Destiny 2',
    slug: 'destiny-2',
    path: '/game/destiny-2',
    imageSrc: '/images/game-covers/destiny-2.jpg',
  },
  {
    id: 49,
    name: 'Warframe',
    slug: 'warframe',
    path: '/game/warframe',
    imageSrc: '/images/game-covers/warframe.jpg',
  },
  {
    id: 50,
    name: 'Path of Exile',
    slug: 'path-of-exile',
    path: '/game/path-of-exile',
    imageSrc: '/images/game-covers/path-of-exile.jpg',
  },
] as const

export const COURSES: ICourseItem[] = [
  {
    course_id: 4,
    course_title: ' path to pro, jakarta - offline',
    course_slug: 'path-to-pro-jakarta-offline',
    course_description:
      '<p>Level up your esports career in just 4 intensive lessons (6 hours each)—just like how the pros do it. Train with access to pro scrims, deep match analysis, monthly performance reviews, career coaching, and real tryout opportunities with MPL/MDL teams.</p><p><br></p><h3><strong>',
    course_image_url:
      'https://propublic-academy.s3.amazonaws.com/course/1747323402_Scarletto.png',
    course_price: '4000000.00',
    order_count: '3',
    course_rating: '0.0000',
  },
  {
    course_id: 1,
    course_title: '1:1 vip coaching - head instuctor: zeys ',
    course_slug: '1:1-vip-coaching-head-instuctor:-zeys',
    course_description:
      '<p>Train with a world-class coach, world champion, and former national team head coach. Get personalized insights, pro-level gameplay analysis, and tailored strategies to reach your goals. Perfect for players serious about leveling up.</p>',
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1747323432_Scarletto.png',
    course_price: '500000.00',
    order_count: '1',
    course_rating: '0.0000',
  },
  {
    course_id: 6,
    course_title: 'test',
    course_slug: 'test',
    course_description: null,
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1750096142_propublic.jpg',
    course_price: '16283000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
  {
    course_id: 5,
    course_title: 'test',
    course_slug: 'test',
    course_description: null,
    course_image_url:
      'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/course/1747409832_Scarletto.png',
    course_price: '16493000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
  {
    course_id: 3,
    course_title: 'rank up - online',
    course_slug: 'rank-up-online',
    course_description:
      "<p>Become a rank god and break past the Mythical wall with 4 high-impact online sessions (3 hours each). Whether you're aiming to go semi-pro in community tournaments or just want to carry your friends and dominate ranked, you'll train like the best—exclusive pro scrims, advanced mechanics, and winning strategies included.</p>",
    course_image_url:
      'https://propublic-academy.s3.amazonaws.com/course/1747323413_Scarletto.png',
    course_price: '490000.00',
    order_count: '0',
    course_rating: '0.0000',
  },
] as const

export const COMMUNITIES: TypeCommunityItem[] = [
  {
    id: 1,
    name: 'Elite Gaming Masters',
    description: 'Mastering the art of competitive gaming',
    author: 'elon',
    members: 1247,
    posts: 89,
    sessions: 12,
    guides: 5,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    isFeatured: true,
    color: 'from-red-600 to-red-700',
    headerImage:
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=200&fit=crop',
  },
  {
    id: 2,
    name: 'Pixel Pioneers',
    description: 'Exploring indie games and hidden gems',
    author: 'gamedev_guru',
    members: 589,
    posts: 42,
    sessions: 8,
    guides: 3,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: false,
    color: 'from-blue-500 to-blue-600',
    headerImage:
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=200&fit=crop',
  },
  {
    id: 3,
    name: 'Strategy Nexus',
    description: 'Deep dives into real-time strategy and turn-based tactics',
    author: 'tactician_x',
    members: 912,
    posts: 67,
    sessions: 10,
    guides: 7,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-green-600 to-green-700',
    headerImage:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop',
  },
  {
    id: 4,
    name: 'Esports Fanatics',
    description: 'Following the latest in professional gaming tournaments',
    author: 'esports_insider',
    members: 2300,
    posts: 150,
    sessions: 20,
    guides: 10,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-purple-600 to-purple-700',
    headerImage:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=200&fit=crop',
  },
  {
    id: 5,
    name: 'Retro Game Revival',
    description: 'Celebrating classic games from the 80s and 90s',
    author: 'vintage_gamer',
    members: 765,
    posts: 55,
    sessions: 6,
    guides: 2,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: false,
    color: 'from-yellow-500 to-yellow-600',
    headerImage:
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=200&fit=crop',
  },
  {
    id: 6,
    name: 'RPG Storytellers',
    description: 'Crafting epic tales in role-playing games',
    author: 'lore_master',
    members: 1050,
    posts: 78,
    sessions: 15,
    guides: 8,
    category: 'GAMING',
    avatar: 'https://avatar.iran.liara.run/public',
    isVerified: true,
    color: 'from-indigo-600 to-indigo-700',
    headerImage:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=200&fit=crop',
  },
]

export const brands: Brand[] = [
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/Bebek+Carok_Long.png',
    name: 'BEBEK CAROK',
    category: 'food',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/ESL+FACEIT_White.png',
    name: 'ESL FACEIT',
    category: 'esports',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/Sekuya.png',
    name: 'SEKUYA',
    category: 'services',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/T1_Red.png',
    name: 'T1',
    category: 'esports',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/Team+Falcon.png',
    name: 'TEAM FALCONS',
    category: 'esports',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/Team+Flash.png',
    name: 'TEAM FLASH',
    category: 'esports',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/Top+Up+No+Limit.png',
    name: 'TOPUP NO LIMIT',
    category: 'services',
  },
  {
    id: Math.random(),
    logo: 'https://propublic-academy.s3.ap-southeast-1.amazonaws.com/partner/W3GG.png',
    name: 'W3GG',
    category: 'services',
  },
]
