name: Claude PR Assistant

on:
  # Trigger for automatic pull request reviews
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-code-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch only the latest code, not the entire history, for speed
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          # Read the Anthropic API key from secrets
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Set a longer timeout to avoid issues with large codebases
          timeout_minutes: "60"
        id: claude-action
